export enum InsertProductScreenTestIdEnum {
  OUTSIDE_CONTAINER = 'OUTSIDE_CONTAINER',
  NAME_INPUT = 'NAME_INPUT',
  IMAGE_INPUT = 'IMAGE_INPUT',
  PRICE_INPUT = 'PRICE_INPUT',
  CATEGORY_SELECT = 'CATEGORY_SELECT',
  INSERT_BUTTON = 'INSERT_BUTTON',
  CANCEL_BUTTON = 'CANCEL_BUTTON',
}
